# Generated by Django 4.0.4 on 2022-05-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default=0, null=True)),
                ('task_name', models.CharField(max_length=89)),
                ('isExternal', models.CharField(default='true', max_length=40)),
                ('splitRatio', models.FloatField(blank=True, default=0.5, null=True)),
                ('rankingAlgorithm', models.CharField(default='fisher', max_length=40)),
                ('vipComponent', models.IntegerField(blank=True, default=0, null=True)),
                ('rocType', models.CharField(default='false', max_length=40)),
                ('tupaType', models.CharField(default='classtupa', max_length=40)),
                ('isMotabo', models.CharField(default='true', max_length=40)),
                ('scaleType', models.CharField(default='autoscale', max_length=40)),
                ('iterations', models.IntegerField(default=1)),
                ('survivalRate', models.FloatField(blank=True, default=0.85, null=True)),
                ('motaboFile', models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/motabo')),
                ('sample_file', models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/sample')),
                ('class_file', models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/class')),
                ('sampleName_file', models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/sampleName')),
                ('variableName_file', models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/variableName')),
                ('project_output', models.FileField(blank=True, null=True, upload_to='featureSelection/out')),
                ('sent_email', models.BooleanField(default=False)),
                ('graph1', models.ImageField(default=0, upload_to='featureSelection/graph1')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(default=0, null=True)),
                ('username', models.CharField(max_length=80, null=True)),
                ('phone', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('sate_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
