# Generated by Django 3.2.1 on 2021-08-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default=0, null=True)),
                ('task_name', models.CharField(max_length=89)),
                ('Rt1', models.IntegerField(null=True)),
                ('Rt2', models.IntegerField(null=True)),
                ('win1', models.IntegerField(null=True)),
                ('win2', models.IntegerField(null=True)),
                ('ms_file', models.FileField(upload_to='project1/ms')),
                ('Library', models.FileField(default=0, upload_to='project1/Lib')),
                ('project_output', models.FileField(blank=True, null=True, upload_to='project1/out')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(default=0, null=True)),
                ('username', models.CharField(max_length=80, null=True)),
                ('phone', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('sate_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
