# Generated by Django 4.0.4 on 2022-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_feature_selection_iterations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_selection',
            name='erro_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
