# Generated by Django 3.0.6 on 2022-09-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20220928_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='others_1dreconstruct',
            name='erro_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
