# Generated by Django 3.2.1 on 2021-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_project_1_ms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_1',
            name='Rt1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='Rt2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='ms_file',
            field=models.FileField(blank=True, null=True, upload_to='project1/ms'),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='win1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='win2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
