# Generated by Django 3.0.6 on 2022-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_others_1dreconstruct_erro_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others_1dreconstruct',
            name='outputFile',
            field=models.FileField(blank=True, null=True, upload_to='others/1dreconstruct/outputFile'),
        ),
    ]
