# Generated by Django 3.2.1 on 2021-08-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20210821_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_1',
            name='ms_file',
            field=models.FileField(blank=True, default=0, null=True, upload_to='project1/ms'),
        ),
    ]
