# Generated by Django 3.0.6 on 2022-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20220928_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_selection',
            name='created_time',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='output_time',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
