# Generated by Django 3.2.1 on 2021-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_project_1_ms_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_1',
            name='single_ms',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
