# Generated by Django 3.0.6 on 2022-10-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20221026_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_selection',
            name='ex_class_file',
            field=models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/class'),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='ex_motaboFile',
            field=models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/motabo'),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='ex_sampleName_file',
            field=models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/sampleName'),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='ex_sample_file',
            field=models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/sample'),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='ex_variableName_file',
            field=models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/variableName'),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='is_externalFile',
            field=models.CharField(blank=True, default='false', max_length=40),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='is_splitRatio',
            field=models.CharField(blank=True, default='true', max_length=40),
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='normType',
            field=models.CharField(default='nonorm', max_length=40),
        ),
        migrations.AlterField(
            model_name='feature_selection',
            name='tupaType',
            field=models.CharField(default='notupa', max_length=40),
        ),
    ]
