# Generated by Django 3.2.1 on 2021-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_project_1_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_1',
            name='Rt1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='Rt2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='win1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_1',
            name='win2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
