# Generated by Django 3.0.6 on 2022-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_feature_selection_is_exmotabo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature_selection',
            name='is_externalFile',
        ),
        migrations.RemoveField(
            model_name='feature_selection',
            name='is_splitRatio',
        ),
        migrations.AddField(
            model_name='feature_selection',
            name='extrnal_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
