# Generated by Django 3.2.1 on 2021-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20210824_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_1',
            name='single_ms',
            field=models.CharField(blank=True, default=0, max_length=10000, null=True),
        ),
    ]
