# Generated by Django 3.2.1 on 2021-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_alter_project_1_single_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_1',
            name='sent_email',
            field=models.BooleanField(default=False),
        ),
    ]
