# Generated by Django 3.2.1 on 2021-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_project_1_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_1',
            name='user_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
