# Generated by Django 3.2.1 on 2021-12-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_project_1_user_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default=0, null=True)),
                ('task_name', models.CharField(max_length=89)),
                ('sample_file', models.FileField(default=0, null=True, upload_to='featureSelection/sample')),
                ('class_file', models.FileField(blank=True, default=0, null=True, upload_to='featureSelection/class')),
                ('project_output', models.FileField(blank=True, null=True, upload_to='featureSlection/out')),
                ('sent_email', models.BooleanField(default=False)),
                ('graph1', models.ImageField(upload_to='featureSelection/graph1')),
            ],
        ),
    ]
