# Generated by Django 3.2.1 on 2021-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_feature_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_selection',
            name='graph1',
            field=models.ImageField(default=0, upload_to='featureSelection/graph1'),
        ),
    ]
